/* global ROADMAP_DATA */
const ROADMAP_DATA = [
  {
    id: 'lv0', label: '— Nível 0 · Ponto de Partida —', badge: 'badge-lv0',
    nodes: [
      {
        id: 'n0', icon: '🔢', title: 'Números e Contagem', sub: 'Naturais, inteiros, zero',
        estimatedHours: 4,
        desc: 'Tudo começa aqui. Números são a linguagem do universo. Você aprende a nomear quantidades, entender o zero (que levou milênios pra ser aceito!) e contar sem limites.',
        topics: ['Números naturais (0, 1, 2, 3...)', 'Linha numérica', 'Comparar e ordenar números', 'O que é o zero?', 'Infinito: existe?'],
        resources: [
          { name: 'Khan Academy — Números inteiros', url: 'https://pt.khanacademy.org/math/cc-sixth-grade-math/cc-6th-factors-and-multiples' },
          { name: 'Nrich — What is a Number?', url: 'https://nrich.maths.org/2671' },
          { name: 'YouTube — O que é o zero? (Canal do Pirulla)', url: 'https://www.youtube.com/watch?v=6nEL6OQQbpE' },
        ],
        questions: [
          { q: 'Qual a diferença entre número natural e número inteiro?', a: 'Naturais são ≥ 0 sem parte negativa (0,1,2,3...). Inteiros incluem os negativos (...-2,-1,0,1,2...).' },
          { q: 'Por que o zero demorou tanto para ser aceito matematicamente?', a: 'Culturas antigas (gregos, romanos) não precisavam de um símbolo para "nada". O zero como número posicional veio da Índia por volta do século VII.' },
          { q: 'Ordene da menor para a maior: -5, 0, 3, -1, 7.', a: '-5, -1, 0, 3, 7.' },
        ],
      },
      {
        id: 'n1', icon: '➕', title: 'Operações Básicas', sub: 'Soma, subtração, multiplicação, divisão',
        estimatedHours: 6,
        requires: ['n0'],
        desc: 'As 4 operações são as ferramentas fundamentais. Tudo mais em matemática é uma combinação dessas quatro.',
        topics: ['Adição e subtração', 'Multiplicação (tabuada)', 'Divisão exata e com resto', 'Propriedades comutativa, associativa, distributiva', 'Ordem das operações (PEMDAS)'],
        resources: [
          { name: 'Khan Academy — Operações aritméticas', url: 'https://pt.khanacademy.org/math/arithmetic' },
          { name: 'Prof. Ferretto — Operações fundamentais', url: 'https://www.youtube.com/@ProfessorFerretto' },
          { name: 'Só Matemática — Propriedades das operações', url: 'https://www.somatematica.com.br/fundam/operacoes.php' },
        ],
        questions: [
          { q: 'Quanto é 3 + 4 × 2? Explique a ordem das operações.', a: '11. Primeiro multiplica: 4×2=8, depois soma: 3+8=11. Multiplicação tem prioridade.' },
          { q: 'Qual a propriedade distributiva? Dê um exemplo.', a: 'a×(b+c) = a×b + a×c. Ex: 3×(4+5) = 3×4 + 3×5 = 12+15 = 27.' },
          { q: 'Qual o resto de 17 ÷ 5?', a: 'Resto 2, pois 5×3=15 e 17-15=2.' },
        ],
      },
      {
        id: 'n2', icon: '🧩', title: 'Frações', sub: 'Partes do todo',
        estimatedHours: 8,
        requires: ['n1'],
        desc: 'Frações existem porque o mundo não é inteiro. Você precisa dividir uma pizza, medir 1/3 de xícara. O conceito de "parte por inteiro" é crucial.',
        topics: ['Numerador e denominador', 'Frações equivalentes', 'Simplificação', 'Soma e subtração de frações', 'Multiplicação e divisão de frações'],
        resources: [
          { name: 'Khan Academy — Frações', url: 'https://pt.khanacademy.org/math/arithmetic/fraction-arithmetic' },
          { name: 'Nrich — Fractions ITP (visual)', url: 'https://nrich.maths.org/5765' },
          { name: 'Matemática Rio — Frações (YouTube)', url: 'https://www.youtube.com/c/matematicario' },
        ],
        questions: [
          { q: 'Simplifique a fração 12/18.', a: '2/3 (divide numerador e denominador por 6, o MDC).' },
          { q: 'Quanto é 1/2 + 1/3?', a: '5/6 — MMC de 2 e 3 é 6: 3/6 + 2/6 = 5/6.' },
          { q: 'Quanto é 3/4 ÷ 1/2?', a: '3/2 ou 1,5 — dividir por fração = multiplicar pelo inverso: 3/4 × 2/1 = 6/4 = 3/2.' },
        ],
      },
      {
        id: 'n3', icon: '💯', title: 'Decimais e Porcentagem', sub: 'Frações no formato decimal',
        estimatedHours: 6,
        requires: ['n2'],
        desc: 'Decimais são frações com denominador potência de 10. Porcentagem é "por cento", literalmente fração com denominador 100.',
        topics: ['Notação decimal', 'Conversão fração ↔ decimal', 'O que é %?', 'Calcular desconto e acréscimo', 'Juros simples básico'],
        resources: [
          { name: 'Khan Academy — Decimais', url: 'https://pt.khanacademy.org/math/arithmetic/arith-decimals' },
          { name: 'Khan Academy — Porcentagem', url: 'https://pt.khanacademy.org/math/pre-algebra/pre-algebra-ratios-rates/pre-algebra-percent-word-problems/a/percent-word-problems' },
          { name: 'Prof. Ferretto — Porcentagem', url: 'https://www.youtube.com/@ProfessorFerretto' },
        ],
        questions: [
          { q: 'Converta 3/8 para decimal.', a: '0,375 — divide 3 por 8.' },
          { q: 'Um produto custa R$200 com 15% de desconto. Qual o valor final?', a: 'R$170 — 15% de 200 = 30; 200-30 = 170.' },
          { q: 'O que significa uma taxa de juros de 2% ao mês?', a: 'Para cada R$100 emprestados, você paga R$2 de juros por mês. Em 6 meses, R$12 de juros simples.' },
        ],
      },
    ],
  },
  {
    id: 'lv1', label: '— Nível 1 · Aritmética —', badge: 'badge-lv1',
    nodes: [
      {
        id: 'n4', icon: '⚡', title: 'Potenciação e Radiciação', sub: 'Multiplicação repetida',
        estimatedHours: 6,
        requires: ['n1'],
        desc: 'Potência é um atalho para multiplicação repetida. 2⁸ = 256. Raiz é a operação inversa. São a base de crescimento exponencial, presente em finanças, biologia e física.',
        topics: ['Potências inteiras', 'Propriedades das potências', 'Raiz quadrada e cúbica', 'Números irracionais (√2)', 'Notação científica'],
        resources: [
          { name: 'Khan Academy — Potências e raízes', url: 'https://pt.khanacademy.org/math/pre-algebra/pre-algebra-exponents-radicals' },
          { name: 'Prof. Ferretto — Potenciação', url: 'https://www.youtube.com/@ProfessorFerretto' },
          { name: 'Wikipedia — Notação científica', url: 'https://pt.wikipedia.org/wiki/Nota%C3%A7%C3%A3o_cient%C3%ADfica' },
        ],
        questions: [
          { q: 'Quanto é 2⁸?', a: '256 — 2×2×2×2×2×2×2×2 = 256.' },
          { q: 'Simplifique: 3⁴ ÷ 3²', a: '3² = 9 — mesma base, subtrai os expoentes: 4-2=2.' },
          { q: 'Por que √2 é irracional?', a: 'Não pode ser escrito como p/q com p,q inteiros. A prova clássica é por contradição.' },
        ],
      },
      {
        id: 'n5', icon: '🔗', title: 'Divisibilidade', sub: 'MMC, MDC, primos',
        estimatedHours: 5,
        requires: ['n1'],
        desc: 'Todo número é feito de "átomos" chamados números primos. O crivo de Eratóstenes é um dos algoritmos mais antigos da história (276 a.C.)!',
        topics: ['Critérios de divisibilidade', 'Números primos', 'Fatoração em primos', 'MMC e MDC', 'Teorema fundamental da Aritmética'],
        resources: [
          { name: 'Khan Academy — Divisibilidade e fatores', url: 'https://pt.khanacademy.org/math/pre-algebra/pre-algebra-factors-multiples' },
          { name: 'Crivo de Eratóstenes — visualização', url: 'https://www.nrich.maths.org/sieve' },
          { name: 'Só Matemática — MMC e MDC', url: 'https://www.somatematica.com.br/fundam/mmc.php' },
        ],
        questions: [
          { q: 'O número 84 é divisível por 4? Justifique.', a: 'Sim. Regra: os dois últimos dígitos (84) são divisíveis por 4: 84÷4=21.' },
          { q: 'Qual o MDC entre 36 e 48?', a: '12 — fatorando: 36=2²×3² e 48=2⁴×3. MDC = 2²×3 = 12.' },
          { q: 'Qual o MMC entre 4, 6 e 9?', a: '36 — MMC = 2²×3² = 36.' },
        ],
      },
      {
        id: 'n6', icon: '⚖️', title: 'Razão e Proporção', sub: 'Relações entre grandezas',
        estimatedHours: 5,
        requires: ['n2'],
        desc: 'Razão é uma comparação. Proporção é quando duas razões são iguais. Escala, velocidade, receitas culinárias — tudo usa proporção.',
        topics: ['Razão a:b', 'Proporções', 'Regra de 3 simples', 'Regra de 3 composta', 'Grandezas diretamente/inversamente proporcionais'],
        resources: [
          { name: 'Khan Academy — Razões e proporções', url: 'https://pt.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic' },
          { name: 'Prof. Ferretto — Regra de 3', url: 'https://www.youtube.com/@ProfessorFerretto' },
          { name: 'Só Matemática — Proporção', url: 'https://www.somatematica.com.br/fundam/proporcao.php' },
        ],
        questions: [
          { q: 'Se 3 maçãs custam R$6, quanto custam 7 maçãs?', a: 'R$14 — regra de 3: 3→6, 7→x. x = 7×6/3 = 14.' },
          { q: 'Explique a diferença entre grandezas direta e inversamente proporcionais.', a: 'Diretas: uma aumenta e a outra aumenta. Inversas: uma aumenta e a outra diminui.' },
          { q: '5 funcionários constroem um muro em 8 dias. Em quantos dias 4 funcionários fariam o mesmo?', a: '10 dias — inversamente proporcional: 5×8 = 4×x → x=10.' },
        ],
      },
    ],
  },
  {
    id: 'lv2', label: '— Nível 2 · Álgebra Básica —', badge: 'badge-lv2',
    nodes: [
      {
        id: 'n7', icon: '🔤', title: 'Variáveis e Expressões', sub: 'Letras em vez de números',
        estimatedHours: 6,
        requires: ['n1'],
        desc: 'Uma variável é um número que você ainda não sabe. A álgebra é a arte de trabalhar com o desconhecido. Einstein usou isso pra chegar em E=mc².',
        topics: ['O que é uma variável?', 'Expressões algébricas', 'Polinômios', 'Fatoração básica', 'Produtos notáveis'],
        resources: [
          { name: 'Khan Academy — Introdução à Álgebra', url: 'https://pt.khanacademy.org/math/algebra' },
          { name: 'Prof. Ferretto — Expressões algébricas', url: 'https://www.youtube.com/@ProfessorFerretto' },
          { name: 'Só Matemática — Polinômios', url: 'https://www.somatematica.com.br/emedio/polinomios.php' },
        ],
        questions: [
          { q: 'Simplifique: 3x + 2y - x + 4y', a: '2x + 6y — agrupa termos semelhantes.' },
          { q: 'Expanda (a+b)²', a: 'a² + 2ab + b² — produto notável quadrado da soma.' },
          { q: 'Fatore x² - 9.', a: '(x+3)(x-3) — diferença de quadrados: a²-b² = (a+b)(a-b).' },
        ],
      },
      {
        id: 'n8', icon: '⚡', title: 'Equações do 1º Grau', sub: 'Achar o valor de x',
        estimatedHours: 6,
        requires: ['n7'],
        desc: 'Uma equação é uma balança: o que você faz de um lado, faz do outro. Resolver equações é o coração da matemática aplicada.',
        topics: ['Princípio da equivalência', 'Equações lineares simples', 'Equações com frações', 'Verificação da solução', 'Problemas contextualizados'],
        resources: [
          { name: 'Khan Academy — Equações de 1º grau', url: 'https://pt.khanacademy.org/math/algebra/x2f8bb11595b61c86:solve-equations-inequalities' },
          { name: 'Prof. Ferretto — Equações do 1º grau', url: 'https://www.youtube.com/@ProfessorFerretto' },
          { name: 'Só Matemática — Equações', url: 'https://www.somatematica.com.br/emedio/equacao1.php' },
        ],
        questions: [
          { q: 'Resolva: 3x + 5 = 20', a: 'x = 5. Subtrai 5 dos dois lados: 3x=15. Divide por 3: x=5.' },
          { q: 'Resolva: x/2 - 1 = 3', a: 'x = 8. Soma 1: x/2=4. Multiplica por 2: x=8.' },
          { q: 'Um número somado ao dobro dele dá 18. Qual é o número?', a: '6. x + 2x = 18 → 3x=18 → x=6.' },
        ],
      },
      {
        id: 'n9', icon: '📐', title: 'Sistemas de Equações', sub: 'Mais de uma equação ao mesmo tempo',
        estimatedHours: 7,
        requires: ['n8'],
        desc: 'Quando você tem dois desconhecidos, precisa de duas equações. Sistemas aparecem em todo cálculo de equilíbrio, mistura e intersecção.',
        topics: ['Método da substituição', 'Método da adição (eliminação)', 'Método gráfico', 'Sistema sem solução / infinitas soluções', 'Aplicações práticas'],
        resources: [
          { name: 'Khan Academy — Sistemas de equações', url: 'https://pt.khanacademy.org/math/algebra/x2f8bb11595b61c86:systems-of-equations' },
          { name: 'Prof. Ferretto — Sistemas lineares', url: 'https://www.youtube.com/@ProfessorFerretto' },
          { name: 'GeoGebra — visualização gráfica de sistemas', url: 'https://www.geogebra.org/graphing' },
        ],
        questions: [
          { q: 'Resolva o sistema: x+y=10, x-y=4', a: 'x=7, y=3. Somando as equações: 2x=14 → x=7.' },
          { q: 'Quando um sistema não tem solução?', a: 'Quando as retas são paralelas. As equações são inconsistentes.' },
          { q: 'Quando um sistema tem infinitas soluções?', a: 'Quando as duas equações representam a mesma reta (uma é múltiplo da outra).' },
        ],
      },
      {
        id: 'n10', icon: '📏', title: 'Inequações', sub: 'Maior, menor, desigualdades',
        estimatedHours: 5,
        requires: ['n8'],
        desc: 'Nem tudo é igual. Inequações definem intervalos onde soluções existem. Fundamentais em otimização e programação linear.',
        topics: ['Símbolos <, >, ≤, ≥', 'Inequações do 1º grau', 'Representação na reta numérica', 'Intervalos', 'Inequações compostas'],
        resources: [
          { name: 'Khan Academy — Inequações', url: 'https://pt.khanacademy.org/math/algebra/x2f8bb11595b61c86:solve-equations-inequalities/x2f8bb11595b61c86:linear-inequalities/a/solving-inequalities-review' },
          { name: 'Prof. Ferretto — Inequações do 1º grau', url: 'https://www.youtube.com/@ProfessorFerretto' },
          { name: 'Só Matemática — Inequações', url: 'https://www.somatematica.com.br/emedio/inequacoes.php' },
        ],
        questions: [
          { q: 'Resolva: 2x - 3 > 5', a: 'x > 4. Soma 3: 2x>8. Divide por 2: x>4.' },
          { q: 'Por que o sinal muda quando multiplicamos por número negativo?', a: 'Porque a ordem se inverte no eixo numérico. Ex: 3 > 1, mas -3 < -1.' },
          { q: 'Expresse em notação de intervalo: x ≥ -2 e x < 5', a: '[-2, 5) — colchete fecha no -2 (inclui), parêntese abre no 5 (não inclui).' },
        ],
      },
    ],
  },
  {
    id: 'lv3', label: '— Nível 3 · Geometria —', badge: 'badge-lv3',
    nodes: [
      {
        id: 'n11', icon: '📐', title: 'Geometria Plana', sub: 'Figuras em 2D',
        estimatedHours: 10,
        requires: ['n4'],
        desc: 'Pitágoras descobriu que em todo triângulo retângulo, a² + b² = c². Esse único teorema é a base da engenharia, arquitetura e GPS.',
        topics: ['Pontos, retas e planos', 'Ângulos', 'Triângulos (Pitágoras!)', 'Quadriláteros e polígonos', 'Circunferência e círculo', 'Área e perímetro'],
        resources: [
          { name: 'Khan Academy — Geometria', url: 'https://pt.khanacademy.org/math/geometry' },
          { name: 'GeoGebra — construções geométricas', url: 'https://www.geogebra.org/geometry' },
          { name: 'Prof. Ferretto — Geometria plana', url: 'https://www.youtube.com/@ProfessorFerretto' },
        ],
        questions: [
          { q: 'Um triângulo retângulo tem catetos 3 e 4. Qual a hipotenusa?', a: '5. Pitágoras: 3²+4²=9+16=25 → √25=5.' },
          { q: 'Qual a área de um círculo de raio 6?', a: '36π ≈ 113,1 — A = πr² = π×36.' },
          { q: 'A soma dos ângulos internos de qualquer triângulo é?', a: '180°.' },
        ],
      },
      {
        id: 'n12', icon: '📦', title: 'Geometria Espacial', sub: 'Figuras em 3D',
        estimatedHours: 8,
        requires: ['n11'],
        desc: 'O mundo real é 3D. Volume de uma caixa, área de uma lata, capacidade de um reservatório — tudo é geometria espacial.',
        topics: ['Prismas e pirâmides', 'Cilindros, cones, esferas', 'Volume e área total', 'Planificação de sólidos', 'Seções transversais'],
        resources: [
          { name: 'Khan Academy — Geometria espacial', url: 'https://pt.khanacademy.org/math/geometry/hs-geo-solids' },
          { name: 'GeoGebra — sólidos 3D', url: 'https://www.geogebra.org/3d' },
          { name: 'Prof. Ferretto — Geometria espacial', url: 'https://www.youtube.com/@ProfessorFerretto' },
        ],
        questions: [
          { q: 'Qual o volume de um cubo de aresta 5?', a: '125 — V = a³ = 5³ = 125.' },
          { q: 'Qual a fórmula do volume de uma esfera?', a: 'V = (4/3)πr³.' },
          { q: 'O que é a planificação de um sólido?', a: '"Abrir" o sólido em uma superfície plana. Útil para calcular área total.' },
        ],
      },
      {
        id: 'n13', icon: '📡', title: 'Trigonometria', sub: 'Seno, cosseno, tangente',
        estimatedHours: 10,
        requires: ['n11'],
        desc: 'Trigonometria nasceu para medir o que não dava pra alcançar. soh-cah-toa é só o começo.',
        topics: ['Triângulo retângulo', 'Seno, cosseno, tangente', 'Lei dos senos e cossenos', 'Ângulos notáveis (30°, 45°, 60°)', 'Aplicações de altura e distância'],
        resources: [
          { name: 'Khan Academy — Trigonometria', url: 'https://pt.khanacademy.org/math/geometry/hs-geo-trig' },
          { name: 'Prof. Ferretto — Trigonometria no triângulo', url: 'https://www.youtube.com/@ProfessorFerretto' },
          { name: 'GeoGebra — círculo trigonométrico', url: 'https://www.geogebra.org/m/XUv5mXTm' },
        ],
        questions: [
          { q: 'Num triângulo retângulo, sen(θ) é definido como?', a: 'Cateto oposto / hipotenusa.' },
          { q: 'Qual o valor de cos(60°)?', a: '0,5 (ou 1/2).' },
          { q: 'Para que serve a lei dos cossenos?', a: 'Para triângulos não-retângulos: c²=a²+b²-2ab·cos(C). Generaliza Pitágoras.' },
        ],
      },
    ],
  },
  {
    id: 'lv4', label: '— Nível 4 · Álgebra Intermediária —', badge: 'badge-lv4',
    nodes: [
      {
        id: 'n14', icon: '🌊', title: 'Equações do 2º Grau', sub: 'Bhaskara e fórmula quadrática',
        estimatedHours: 8,
        requires: ['n8', 'n4'],
        desc: 'ax² + bx + c = 0. A fórmula de Bhaskara veio do matemático indiano Brahmagupta. O discriminante Δ decide tudo.',
        topics: ['Forma geral ax²+bx+c', 'Fórmula de Bhaskara', 'Discriminante Δ', 'Produto e soma das raízes (Viète)', 'Equações biquadráticas'],
        resources: [
          { name: 'Khan Academy — Equações quadráticas', url: 'https://pt.khanacademy.org/math/algebra/x2f8bb11595b61c86:quadratics-multiplying-factoring' },
          { name: 'Prof. Ferretto — Equações do 2º grau', url: 'https://www.youtube.com/@ProfessorFerretto' },
          { name: 'Desmos — exploração de parábolas', url: 'https://www.desmos.com/calculator' },
        ],
        questions: [
          { q: 'Resolva x² - 5x + 6 = 0', a: 'x=2 e x=3. Δ=25-24=1. x=(5±1)/2.' },
          { q: 'O que Δ < 0 significa?', a: 'A equação não tem raízes reais — só raízes complexas.' },
          { q: 'Pelas relações de Viète, qual a soma e o produto das raízes de x²-7x+12=0?', a: 'Soma = 7 (= -b/a), produto = 12 (= c/a). As raízes são 3 e 4.' },
        ],
      },
      {
        id: 'n15', icon: '📈', title: 'Funções', sub: 'Relações de entrada e saída',
        estimatedHours: 10,
        requires: ['n8'],
        desc: 'Uma função é uma máquina: entra x, sai f(x). Funções descrevem todo fenômeno do mundo: temperatura, crescimento, lucro.',
        topics: ['Definição de função', 'Domínio, contradomínio e imagem', 'Função afim (linear)', 'Função quadrática (parábola)', 'Gráficos e transformações'],
        resources: [
          { name: 'Khan Academy — Funções', url: 'https://pt.khanacademy.org/math/algebra/x2f8bb11595b61c86:functions' },
          { name: 'Desmos — explorador de funções', url: 'https://www.desmos.com/calculator' },
          { name: 'Prof. Ferretto — Funções', url: 'https://www.youtube.com/@ProfessorFerretto' },
        ],
        questions: [
          { q: 'f(x) = 2x+1. Qual f(3)?', a: '7. f(3) = 2×3+1 = 7.' },
          { q: 'Qual a diferença entre contradomínio e imagem?', a: 'Contradomínio é o conjunto de valores possíveis. Imagem é o que a função realmente assume.' },
          { q: 'A parábola y=x²-4x+3 abre para cima ou para baixo?', a: 'Para cima. O coeficiente a=1 > 0 indica concavidade voltada para cima.' },
        ],
      },
      {
        id: 'n16', icon: '📉', title: 'Funções Exponenciais e Log', sub: 'Crescimento e escala',
        estimatedHours: 8,
        requires: ['n15', 'n4'],
        desc: 'Exponencial descreve vírus, dívidas e explosões nucleares. Logaritmo é o inverso — a escala de decibéis é logarítmica.',
        topics: ['f(x) = aˣ', 'Propriedades da exponencial', 'Definição de logaritmo', 'Propriedades do log', 'log natural (ln) e número e'],
        resources: [
          { name: 'Khan Academy — Funções exponenciais e log', url: 'https://pt.khanacademy.org/math/algebra2/x2ec2f6f830c9fb89:logs' },
          { name: 'Prof. Ferretto — Logaritmos', url: 'https://www.youtube.com/@ProfessorFerretto' },
          { name: '3Blue1Brown — e e a função exponencial', url: 'https://www.youtube.com/watch?v=m2MIpDrF7Es' },
        ],
        questions: [
          { q: 'Quanto é log₂(8)?', a: '3, pois 2³ = 8.' },
          { q: 'O número e ≈ 2,718 aparece naturalmente onde?', a: 'Em crescimento contínuo (juros compostos instantâneos), derivadas, e na fórmula de Euler.' },
          { q: 'Simplifique: log(100) + log(10)', a: 'log₁₀(100)+log₁₀(10) = 2+1 = 3.' },
        ],
      },
      {
        id: 'n17', icon: '🔢', title: 'PA e PG', sub: 'Sequências e progressões',
        estimatedHours: 6,
        requires: ['n15'],
        desc: 'Progressões aritmética (razão constante por soma) e geométrica (razão constante por multiplicação). Juros compostos é uma PG.',
        topics: ['Sequências numéricas', 'PA: definição e fórmulas', 'PG: definição e fórmulas', 'Soma dos termos', 'Aplicação em juros compostos'],
        resources: [
          { name: 'Khan Academy — Sequências', url: 'https://pt.khanacademy.org/math/algebra/x2f8bb11595b61c86:sequences' },
          { name: 'Prof. Ferretto — PA e PG', url: 'https://www.youtube.com/@ProfessorFerretto' },
          { name: 'Só Matemática — Progressões', url: 'https://www.somatematica.com.br/emedio/progressoes.php' },
        ],
        questions: [
          { q: 'Qual o décimo termo da PA (2, 5, 8, ...)?', a: '29. aₙ = a₁+(n-1)r = 2+9×3 = 29.' },
          { q: 'Uma PG tem a₁=2 e razão q=3. Qual o 5º termo?', a: '162. aₙ = a₁×qⁿ⁻¹ = 2×3⁴ = 162.' },
          { q: 'Por que juros compostos formam uma PG?', a: 'O montante se multiplica pelo mesmo fator (1+i) a cada período: M = C×(1+i)ⁿ.' },
        ],
      },
    ],
  },
  {
    id: 'lv5', label: '— Nível 5 · Pré-Cálculo —', badge: 'badge-lv5',
    nodes: [
      {
        id: 'n18', icon: '🌀', title: 'Trigonometria Avançada', sub: 'Ciclo trigonométrico',
        estimatedHours: 10,
        requires: ['n13', 'n15'],
        desc: 'Seno e cosseno são funções periódicas — descrevem ondas de som, luz, eletricidade. O círculo unitário unifica tudo.',
        topics: ['Ciclo trigonométrico', 'Funções sen, cos, tg e inversas', 'Identidades trigonométricas', 'Fórmulas de adição', 'Equações trigonométricas'],
        resources: [
          { name: 'Khan Academy — Trigonometria avançada', url: 'https://pt.khanacademy.org/math/trigonometry' },
          { name: 'GeoGebra — ciclo trigonométrico animado', url: 'https://www.geogebra.org/m/XUv5mXTm' },
          { name: '3Blue1Brown — But what is a Fourier series?', url: 'https://www.youtube.com/watch?v=r6sGWTCMz2k' },
        ],
        questions: [
          { q: 'Qual a identidade fundamental da trigonometria?', a: 'sen²(x) + cos²(x) = 1.' },
          { q: 'Qual o período da função sen(x)?', a: '2π — ela completa um ciclo a cada 2π radianos.' },
          { q: 'Expanda cos(A+B).', a: 'cos(A)cos(B) - sen(A)sen(B).' },
        ],
      },
      {
        id: 'n19', icon: '🔮', title: 'Números Complexos', sub: 'A raiz de -1 existe!',
        estimatedHours: 8,
        requires: ['n14'],
        desc: 'i = √(-1). Parece mentira, mas números complexos são a base da engenharia elétrica, mecânica quântica e processamento de sinais.',
        topics: ['Definição de i', 'Forma algébrica a+bi', 'Operações com complexos', 'Módulo e argumento', 'Fórmula de Euler: eⁱˣ = cos x + i·sen x'],
        resources: [
          { name: 'Khan Academy — Números complexos', url: 'https://pt.khanacademy.org/math/algebra2/x2ec2f6f830c9fb89:complex' },
          { name: '3Blue1Brown — Números complexos e transformações', url: 'https://www.youtube.com/watch?v=5PcpBw5Hbwo' },
          { name: 'Prof. Ferretto — Números complexos', url: 'https://www.youtube.com/@ProfessorFerretto' },
        ],
        questions: [
          { q: 'Quanto é i²?', a: '-1 — por definição de i.' },
          { q: 'Calcule (2+3i)(1-i).', a: '5+i. Expandindo: 2-2i+3i-3i² = 2+i+3 = 5+i.' },
          { q: 'Qual o módulo de 3+4i?', a: '5. |z| = √(3²+4²) = √25 = 5.' },
        ],
      },
      {
        id: 'n20', icon: '🎲', title: 'Combinatória', sub: 'Contar sem listar',
        estimatedHours: 8,
        requires: ['n5'],
        desc: 'Quantas senhas de 4 dígitos existem? Quantas mãos no poker? Combinatória responde isso de forma exata e elegante.',
        topics: ['Princípio Fundamental da Contagem', 'Fatorial', 'Permutações', 'Combinações', 'Binômio de Newton'],
        resources: [
          { name: 'Khan Academy — Combinatória', url: 'https://pt.khanacademy.org/math/statistics-probability/counting-permutations-and-combinations' },
          { name: 'Prof. Ferretto — Análise combinatória', url: 'https://www.youtube.com/@ProfessorFerretto' },
          { name: 'Só Matemática — Combinações', url: 'https://www.somatematica.com.br/emedio/combinatoria.php' },
        ],
        questions: [
          { q: 'De quantas formas podemos organizar as letras de "CASA"?', a: '12. 4!/2! = 24/2 = 12 (o "A" se repete 2x).' },
          { q: 'Quantas combinações de 2 pessoas existem num grupo de 5?', a: 'C(5,2) = 10.' },
          { q: 'Qual a diferença entre permutação e combinação?', a: 'Na permutação a ordem importa. Na combinação não.' },
        ],
      },
      {
        id: 'n21', icon: '📊', title: 'Probabilidade e Estatística', sub: 'Incerteza com precisão',
        estimatedHours: 10,
        requires: ['n20'],
        desc: 'Probabilidade quantifica o acaso. Estatística resume dados. Juntas são a base da ciência moderna, medicina e IA.',
        topics: ['Espaço amostral e eventos', 'P(A) e regras básicas', 'Média, mediana, moda', 'Desvio padrão e variância', 'Distribuições: normal, binomial'],
        resources: [
          { name: 'Khan Academy — Probabilidade e Estatística', url: 'https://pt.khanacademy.org/math/statistics-probability' },
          { name: 'StatQuest — Statistics Fundamentals', url: 'https://www.youtube.com/@statquest' },
          { name: 'Prof. Ferretto — Probabilidade', url: 'https://www.youtube.com/@ProfessorFerretto' },
        ],
        questions: [
          { q: 'Qual a probabilidade de tirar cara duas vezes em dois lançamentos?', a: '1/4 = 25%. Eventos independentes: P = 1/2 × 1/2.' },
          { q: 'Qual a diferença entre média e mediana?', a: 'Média é a soma dividida pelo total. Mediana é o valor central. Mediana é menos sensível a outliers.' },
          { q: 'O que o desvio padrão mede?', a: 'A dispersão dos dados em torno da média.' },
        ],
      },
    ],
  },
  {
    id: 'lv6', label: '— Nível 6 · Cálculo —', badge: 'badge-lv6',
    nodes: [
      {
        id: 'n22', icon: '🔭', title: 'Limites', sub: 'O que acontece quando x → a',
        estimatedHours: 12,
        requires: ['n15', 'n18'],
        desc: 'Limite é perguntar: "pra onde vai a função enquanto x se aproxima de algo?" Newton e Leibniz inventaram o cálculo para descrever movimento.',
        topics: ['Conceito intuitivo de limite', 'Limites laterais', 'Limites no infinito', 'Formas indeterminadas', 'Continuidade de funções'],
        resources: [
          { name: 'Khan Academy — Limites (Cálculo AB)', url: 'https://pt.khanacademy.org/math/ap-calculus-ab/ab-limits-new' },
          { name: '3Blue1Brown — Essence of Calculus', url: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr' },
          { name: "Paul's Online Math Notes — Limits", url: 'https://tutorial.math.lamar.edu/Classes/CalcI/LimitsIntro.aspx' },
        ],
        questions: [
          { q: 'Qual é lim(x→2) de (x² - 4) / (x-2)?', a: '4. Simplificando: (x-2)(x+2)/(x-2) = x+2 → quando x→2: 4.' },
          { q: 'O que é uma forma indeterminada?', a: 'Expressão como 0/0 ou ∞/∞ que precisa de álgebra ou L\'Hôpital para ser avaliada.' },
          { q: 'Uma função é contínua em x=a se satisfaz quais 3 condições?', a: 'f(a) existe; lim(x→a) f(x) existe; e lim(x→a) f(x) = f(a).' },
        ],
      },
      {
        id: 'n23', icon: '📐', title: 'Derivadas', sub: 'Taxa de variação instantânea',
        estimatedHours: 14,
        requires: ['n22'],
        desc: 'Derivada é a inclinação da curva num ponto. Velocidade é derivada da posição. Aceleração é derivada da velocidade.',
        topics: ['Definição via limite', 'Regras (produto, quociente, cadeia)', 'Derivadas elementares', 'Máximos e mínimos', 'Aplicações: otimização'],
        resources: [
          { name: 'Khan Academy — Derivadas', url: 'https://pt.khanacademy.org/math/ap-calculus-ab/ab-differentiation-1-new' },
          { name: '3Blue1Brown — Derivatives', url: 'https://www.youtube.com/watch?v=9vKqVkMQHKk' },
          { name: "Paul's Online Math Notes — Derivatives", url: 'https://tutorial.math.lamar.edu/Classes/CalcI/DerivativeIntro.aspx' },
        ],
        questions: [
          { q: 'Qual a derivada de f(x) = x³?', a: "f'(x) = 3x². Regra da potência: d/dx(xⁿ) = nxⁿ⁻¹." },
          { q: 'Qual a regra da cadeia?', a: "d/dx[f(g(x))] = f'(g(x))·g'(x). Ex: d/dx[sin(x²)] = cos(x²)·2x." },
          { q: 'Como a derivada ajuda a encontrar máximos e mínimos?', a: "Em pontos extremos, f'(x)=0. Se f''(x)<0 é máximo; se f''(x)>0 é mínimo." },
        ],
      },
      {
        id: 'n24', icon: '🌊', title: 'Integrais', sub: 'Área sob a curva',
        estimatedHours: 14,
        requires: ['n23'],
        desc: 'Integral é a operação inversa da derivada (Teorema Fundamental do Cálculo). Calcula área, volume, trabalho, probabilidade.',
        topics: ['Integral como área', 'Integral indefinida e definida', 'Regras de integração', 'Integração por substituição', 'Integral por partes'],
        resources: [
          { name: 'Khan Academy — Integrais', url: 'https://pt.khanacademy.org/math/ap-calculus-ab/ab-integration-new' },
          { name: '3Blue1Brown — Integration and the fundamental theorem', url: 'https://www.youtube.com/watch?v=rfG8ce4nNh0' },
          { name: 'WolframAlpha — calcular integrais', url: 'https://www.wolframalpha.com/calculators/integral-calculator/' },
        ],
        questions: [
          { q: 'Qual ∫x² dx?', a: 'x³/3 + C. Regra da potência invertida: ∫xⁿdx = xⁿ⁺¹/(n+1) + C.' },
          { q: 'O que diz o Teorema Fundamental do Cálculo?', a: '∫ₐᵇ f(x)dx = F(b)-F(a), onde F é a antiderivada de f.' },
          { q: 'Calcule ∫₀² x dx.', a: '2. F(x)=x²/2. F(2)-F(0) = 2-0 = 2.' },
        ],
      },
      {
        id: 'n25', icon: '🌀', title: 'Equações Diferenciais', sub: 'Equações com derivadas',
        estimatedHours: 16,
        requires: ['n24'],
        desc: 'A física do universo é escrita em EDOs. F=ma é uma equação diferencial. Crescimento populacional, circuitos elétricos, calor.',
        topics: ['O que é uma EDO?', 'EDOs de 1ª ordem separáveis', 'EDOs lineares com coeficiente constante', 'Modelo de crescimento (Malthus)', 'Circuitos RC e osciladores'],
        resources: [
          { name: 'Khan Academy — Equações diferenciais', url: 'https://pt.khanacademy.org/math/differential-equations' },
          { name: '3Blue1Brown — Differential equations overview', url: 'https://www.youtube.com/watch?v=p_di4Zn4wz4' },
          { name: "Paul's Online Math Notes — Differential Equations", url: 'https://tutorial.math.lamar.edu/Classes/DE/DE.aspx' },
        ],
        questions: [
          { q: "Resolva dy/dx = y.", a: 'y = Ceˣ. Separando: dy/y = dx → ln|y|=x+c → y=Ceˣ.' },
          { q: 'O modelo de Malthus dP/dt = rP descreve o quê?', a: 'Crescimento exponencial: população cresce proporcionalmente ao seu tamanho. P(t)=P₀eʳᵗ.' },
          { q: 'O que é uma equação diferencial de ordem 2?', a: 'Tem a segunda derivada. Ex: F=ma → m·d²x/dt² = F(x,t).' },
        ],
      },
    ],
  },
  {
    id: 'lv7', label: '— Nível 7 · Álgebra Linear —', badge: 'badge-lv7',
    nodes: [
      {
        id: 'n26', icon: '➡️', title: 'Vetores', sub: 'Grandezas com direção',
        estimatedHours: 10,
        requires: ['n11'],
        desc: 'Vetores têm magnitude e direção. São a linguagem da física, computação gráfica e ML. Todo embedding de IA é um vetor.',
        topics: ['Definição e notação', 'Operações: soma e escalar', 'Produto escalar (dot product)', 'Produto vetorial (cross product)', 'Projeção e ortogonalidade'],
        resources: [
          { name: 'Khan Academy — Vetores', url: 'https://pt.khanacademy.org/math/linear-algebra/vectors-and-spaces' },
          { name: '3Blue1Brown — Vectors (Essence of Linear Algebra)', url: 'https://www.youtube.com/watch?v=fNk_zzaMoSs' },
          { name: 'GeoGebra — operações com vetores', url: 'https://www.geogebra.org/m/GuYQ8qeV' },
        ],
        questions: [
          { q: 'Calcule o produto escalar de (1,2,3) e (4,5,6).', a: '32. 1×4 + 2×5 + 3×6 = 4+10+18 = 32.' },
          { q: 'Dois vetores são ortogonais se o produto escalar é?', a: 'Zero. u·v = 0 ↔ vetores perpendiculares.' },
          { q: 'O que representa o produto escalar de dois vetores unitários?', a: 'O cosseno do ângulo entre eles: u·v = cos(θ).' },
        ],
      },
      {
        id: 'n27', icon: '🟩', title: 'Matrizes', sub: 'Grades de números',
        estimatedHours: 12,
        requires: ['n9', 'n26'],
        desc: 'Matrizes organizam sistemas de equações. São o coração de transformações lineares, redes neurais e gráficos 3D.',
        topics: ['Definição e operações', 'Multiplicação de matrizes', 'Matriz transposta e inversa', 'Determinante', 'Sistemas lineares via matrizes (Gauss)'],
        resources: [
          { name: 'Khan Academy — Matrizes', url: 'https://pt.khanacademy.org/math/precalculus/x9e81a4f98389efdf:matrices' },
          { name: '3Blue1Brown — Linear transformations and matrices', url: 'https://www.youtube.com/watch?v=kYB8IZa5AuE' },
          { name: 'Prof. Ferretto — Matrizes e determinantes', url: 'https://www.youtube.com/@ProfessorFerretto' },
        ],
        questions: [
          { q: 'A multiplicação de matrizes é comutativa?', a: 'Não. Em geral AB ≠ BA.' },
          { q: 'O que significa det(A) = 0?', a: 'A matriz é singular (não invertível). O sistema pode não ter solução única.' },
          { q: 'Para que serve a eliminação gaussiana?', a: 'Para resolver sistemas lineares Ax=b, transformando a matriz aumentada em forma escalonada.' },
        ],
      },
      {
        id: 'n28', icon: '🔁', title: 'Espaços Vetoriais', sub: 'Estrutura abstrata',
        estimatedHours: 12,
        requires: ['n27'],
        desc: 'Um espaço vetorial é qualquer conjunto com soma e escalar que obedecem certas regras. Funções, polinômios e matrizes são espaços vetoriais!',
        topics: ['Axiomas do espaço vetorial', 'Subespaços', 'Base e dimensão', 'Independência linear', 'Transformações lineares'],
        resources: [
          { name: 'Khan Academy — Espaços vetoriais', url: 'https://pt.khanacademy.org/math/linear-algebra/vectors-and-spaces/subspace-basis/v/linear-subspaces' },
          { name: '3Blue1Brown — Abstract vector spaces', url: 'https://www.youtube.com/watch?v=TgKwz5Ikpc8' },
          { name: 'MIT OpenCourseWare — Linear Algebra (Gilbert Strang)', url: 'https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/' },
        ],
        questions: [
          { q: 'Os vetores (1,0) e (0,1) formam uma base do ℝ²? Por quê?', a: 'Sim. São linearmente independentes e geram todo o ℝ².' },
          { q: 'O que é a dimensão de um espaço vetorial?', a: 'O número de vetores em qualquer base. Ex: ℝ³ tem dimensão 3.' },
          { q: 'Quando dois vetores são linearmente dependentes?', a: 'Quando um é múltiplo escalar do outro — são paralelos.' },
        ],
      },
      {
        id: 'n29', icon: '🎯', title: 'Autovalores e Autovetores', sub: 'A geometria das transformações',
        estimatedHours: 12,
        requires: ['n28'],
        desc: 'Autovetores são as direções que uma transformação não "vira" — só escala. PageRank do Google e PCA em IA usam isso.',
        topics: ['Definição de autovalor λ', 'Equação característica', 'Diagonalização', 'Decomposição espectral', 'Aplicação em PCA e Machine Learning'],
        resources: [
          { name: '3Blue1Brown — Eigenvectors and eigenvalues', url: 'https://www.youtube.com/watch?v=PFDu9oVAE-g' },
          { name: 'MIT OpenCourseWare — Eigenvalues (Strang)', url: 'https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/pages/video-lectures/lecture-21-eigenvalues-and-eigenvectors/' },
          { name: 'Khan Academy — Eigenvectors and eigenvalues', url: 'https://pt.khanacademy.org/math/linear-algebra/alternate-bases/eigen-everything/v/linear-algebra-introduction-to-eigenvalues-and-eigenvectors' },
        ],
        questions: [
          { q: 'Intuitivamente, o que é um autovetor?', a: 'Um vetor que, ao passar pela transformação A, só muda de escala: Av = λv.' },
          { q: 'Como se calcula o autovalor?', a: 'Resolvendo det(A - λI) = 0 — equação característica.' },
          { q: 'O que é PCA e como usa autovetores?', a: 'Reduz dimensionalidade encontrando as direções de maior variância — os autovetores da matriz de covariância.' },
        ],
      },
    ],
  },
  {
    id: 'lv8', label: '— Nível 8 · Matemática Avançada —', badge: 'badge-lv8',
    nodes: [
      {
        id: 'n30', icon: '🧠', title: 'Análise Real', sub: 'O rigor por trás do Cálculo',
        estimatedHours: 20,
        requires: ['n24'],
        desc: 'Análise Real é o Cálculo com prova formal. Aqui você entende o que "limite" significa de verdade, com épsilons e deltas.',
        topics: ['Sequências e séries convergentes', 'Definição ε-δ de limite', 'Teorema do Valor Intermediário', 'Completude dos reais', 'Integração de Riemann'],
        resources: [
          { name: 'Abbott — Understanding Analysis (Springer)', url: 'https://link.springer.com/book/10.1007/978-1-4939-2712-8' },
          { name: 'MIT OCW — Real Analysis', url: 'https://ocw.mit.edu/courses/18-100b-analysis-i-fall-2010/' },
          { name: 'YouTube — Real Analysis (Francis Su)', url: 'https://www.youtube.com/playlist?list=PL0E754696F72137EC' },
        ],
        questions: [
          { q: 'Defina limite via ε-δ.', a: 'lim(x→a)f(x)=L se: para todo ε>0, existe δ>0 tal que 0<|x-a|<δ implica |f(x)-L|<ε.' },
          { q: 'O que afirma o Teorema do Valor Intermediário?', a: 'Se f é contínua em [a,b] e f(a)<c<f(b), então existe x∈(a,b) com f(x)=c.' },
          { q: 'Por que os racionais não formam um conjunto "completo"?', a: 'Existem sequências de Cauchy de racionais que convergem para irracionais (ex: √2).' },
        ],
      },
      {
        id: 'n31', icon: '🔣', title: 'Álgebra Abstrata', sub: 'Grupos, anéis e corpos',
        estimatedHours: 20,
        requires: ['n28'],
        desc: 'Grupos são estruturas com uma operação e 4 axiomas. Descrevem simetrias da física de partículas e criptografia RSA.',
        topics: ['Grupos e subgrupos', 'Homomorfismos', 'Anéis e ideais', 'Corpos (fields)', 'Teoria de Galois (noção)'],
        resources: [
          { name: 'Visual Group Theory — YouTube', url: 'https://www.youtube.com/watch?v=UwTQdOop-nU' },
          { name: 'MIT OCW — Abstract Algebra', url: 'https://ocw.mit.edu/courses/18-703-modern-algebra-spring-2013/' },
          { name: 'Artin — Algebra (Pearson)', url: 'https://www.pearson.com/en-us/subject-catalog/p/algebra/P200000006179' },
        ],
        questions: [
          { q: 'Quais os 4 axiomas de um grupo?', a: 'Fechamento, associatividade, elemento neutro e elemento inverso.' },
          { q: 'Os inteiros ℤ formam um grupo sob adição?', a: 'Sim. Fechamento (a+b∈ℤ), associativo, neutro (0), inverso (-a).' },
          { q: 'Qual a relação entre grupos e criptografia RSA?', a: 'RSA usa o grupo multiplicativo de inteiros mod n. A dificuldade de fatoração de n garante a segurança.' },
        ],
      },
      {
        id: 'n32', icon: '🌐', title: 'Topologia', sub: 'Geometria sem distância',
        estimatedHours: 18,
        requires: ['n30'],
        desc: 'Topologia estuda o que não muda quando você estica ou dobra um espaço (sem rasgar). Uma xícara e uma rosquinha são topologicamente idênticas!',
        topics: ['Espaços métricos', 'Espaços topológicos', 'Continuidade topológica', 'Compacidade e conexidade', 'Noção de homeomorfismo'],
        resources: [
          { name: 'Munkres — Topology (Pearson)', url: 'https://www.pearson.com/en-us/subject-catalog/p/topology/P200000006216' },
          { name: 'YouTube — Topology (Tadashi Tokieda)', url: 'https://www.youtube.com/watch?v=SXHHvoaSctA' },
          { name: 'MIT OCW — Topology I', url: 'https://ocw.mit.edu/courses/18-901-introduction-to-topology-fall-2004/' },
        ],
        questions: [
          { q: 'O que é um homeomorfismo?', a: 'Uma bijeção contínua com inversa contínua. Dois espaços homeomorfos são topologicamente iguais.' },
          { q: 'Por que uma xícara e uma rosquinha são o mesmo objeto em topologia?', a: 'Ambas têm exatamente 1 buraco passante (gênero 1). Existe homeomorfismo entre elas.' },
          { q: 'O que é um espaço compacto (intuição)?', a: 'Generalização de "fechado e limitado". Em espaços métricos, toda sequência tem subsequência convergente.' },
        ],
      },
      {
        id: 'n33', icon: '📡', title: 'Cálculo Multivariável', sub: 'Funções de ℝⁿ → ℝᵐ',
        estimatedHours: 18,
        requires: ['n24', 'n27'],
        desc: 'O mundo tem mais de uma variável. Gradiente, divergente, rotacional — base da física e do deep learning.',
        topics: ['Funções de 2+ variáveis', 'Derivadas parciais', 'Gradiente e plano tangente', 'Integrais duplas e triplas', 'Teoremas de Green, Stokes, Gauss'],
        resources: [
          { name: 'Khan Academy — Cálculo Multivariável', url: 'https://pt.khanacademy.org/math/multivariable-calculus' },
          { name: '3Blue1Brown — Gradient descent (ML context)', url: 'https://www.youtube.com/watch?v=IHZwWFHWa-w' },
          { name: 'MIT OCW — Multivariable Calculus (Denis Auroux)', url: 'https://ocw.mit.edu/courses/18-02-multivariable-calculus-fall-2007/' },
        ],
        questions: [
          { q: 'O que é a derivada parcial ∂f/∂x?', a: 'A taxa de variação de f em relação a x, mantendo todas as outras variáveis constantes.' },
          { q: 'O gradiente ∇f aponta em qual direção?', a: 'Na direção de maior crescimento de f. Em ML, guia o ajuste dos pesos (gradient descent).' },
          { q: 'O que o Teorema de Stokes relaciona?', a: 'A integral de linha ao longo de uma curva fechada e a integral de superfície do rotacional.' },
        ],
      },
      {
        id: 'n34', icon: '🎲', title: 'Probabilidade Avançada', sub: 'Teoria da medida e processos',
        estimatedHours: 20,
        requires: ['n21', 'n30'],
        desc: 'Probabilidade formal usa teoria da medida. Processos estocásticos descrevem o mercado financeiro, difusão de moléculas e passeios aleatórios.',
        topics: ['Sigma-álgebras e medida', 'Variáveis aleatórias contínuas', 'Distribuições avançadas', 'Processos de Markov', 'Movimento Browniano'],
        resources: [
          { name: 'MIT OCW — Probability and Random Variables', url: 'https://ocw.mit.edu/courses/18-650-statistics-for-applications-fall-2016/' },
          { name: 'YouTube — Stochastic Processes (NPTEL)', url: 'https://www.youtube.com/playlist?list=PLbMVogVj5nJQpKd-9QdSsZlgbKiDMkbeJ' },
          { name: 'Durrett — Probability: Theory and Examples (PDF)', url: 'https://services.math.duke.edu/~rtd/PTE/PTE5_011119.pdf' },
        ],
        questions: [
          { q: 'O que é uma sigma-álgebra?', a: 'Coleção de subconjuntos fechada sob complemento e uniões contáveis. Define quais eventos têm probabilidade.' },
          { q: 'O que é uma Cadeia de Markov?', a: 'Processo estocástico onde o estado futuro depende apenas do estado atual ("sem memória"). Ex: PageRank.' },
          { q: 'Qual a importância do Movimento Browniano?', a: 'Modelo do movimento aleatório contínuo. Base da equação de Black-Scholes e modelos de difusão em física e ML.' },
        ],
      },
    ],
  },
];
